abc/Areas/Admin/Controllers/ThongKeController.cs
using Models.Dao;
using Models.Framework;
using Models.ViewModel;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace abc.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
		// GET: Admin/ThongKe
		DoAnDbContext db = new DoAnDbContext();
		public ActionResult Index(string searchYeuCau, string searchTinhTrang, string searchName,
			string searchTenDanhMuc, string searchTenDonVi, string searchTenLop, string searchEmail, string searchTenVaiTro, int page = 1, int pageSize = 10)
        {
			var dao = new HocVuDao();
			var model = dao.ListThongKe(searchYeuCau, searchTinhTrang, searchName, searchTenDanhMuc,
				searchTenDonVi, searchTenLop, searchEmail, searchTenVaiTro, page, pageSize);
			var dao1 = new DonViDao();
			ViewBag.listDonVi = new SelectList(dao1.ListAll(), "TenDonVi", "TenDonVi");
			ViewBag.listTinhTrang = new SelectList(dao.ListAll(), "TinhTrang", "TinhTrang");
			var lop = new LopDao();
			ViewBag.listLop = new SelectList(lop.ListAll(), "TenLop", "TenLop");
			var vaitro = new VaiTroDao();
			ViewBag.listVaiTro = new SelectList(vaitro.ListAll(), "TenVaiTro", "TenVaiTro");
			ViewBag.searchYeuCau = searchYeuCau;
			ViewBag.searchTinhTrang = searchTinhTrang;
			ViewBag.searchName = searchName;
			ViewBag.searchTenDanhMuc = searchTenDanhMuc;
			ViewBag.searchTenDonVi = searchTenDonVi;
			ViewBag.searchTenLop = searchTenLop;
			ViewBag.searchEmail = searchEmail;
			ViewBag.searchTenVaiTro = searchTenVaiTro;

			var list = dao.ListAll();
			List<int> repart = new List<int>();
			var userID = list.Select(x => x.UserID).Distinct();
			var listUser = from a in userID
						  join b in db.Users on a.Value equals b.UserID
						  select b.UserName;
			foreach (var item in userID)
			{
				repart.Add(list.Count(x => x.UserID == item));
			}
			var rep = repart;
			ViewBag.UserID = listUser;
			ViewBag.REP = repart.ToList();


			var danhmucID = list.Select(x => x.DanhMucID).Distinct();
			var listDM = from a in danhmucID
						join b in db.DanhMucs on a.ToString() equals b.DanhMucID.ToString()
						   select b.TenDanhMuc;
			List<int> listDanhMuc = new List<int>();
			foreach (var item in danhmucID)
			{
				listDanhMuc.Add(list.Count(x => x.DanhMucID == item));
			}
			ViewBag.danhmucID = listDM;
			ViewBag.listDanhMuc = listDanhMuc.ToList();
			return View(model);
		}
		public JsonResult GetDanhMucList(string TenDonVi)
		{
			db.Configuration.ProxyCreationEnabled = false;
			var getDVID = from q in db.DonVis
						  where (q.TenDonVi == TenDonVi)
						  select q.DonViID;
			List<DanhMuc> DanhMucList = db.DanhMucs.Where(x => x.DonViID == getDVID.Max()).ToList();
			return Json(DanhMucList, JsonRequestBehavior.AllowGet);
		}
		public ActionResult PrintAll(string searchYeuCau, string searchTinhTrang, string searchName,
			string searchTenDanhMuc, string searchTenDonVi, string searchTenLop, string searchEmail, string searchTenVaiTro)
		{
			var dao = new HocVuDao();
			var model = dao.ListThongKe(searchYeuCau, searchTinhTrang, searchName, searchTenDanhMuc,
				searchTenDonVi, searchTenLop, searchEmail, searchTenVaiTro, 1, 10);

			var q = new ActionAsPdf("Index", model);
			var b = new ViewAsPdf("Index", model);
			var a = new PartialViewAsPdf("Index", model);
			return b;
		}
		public ActionResult GetData()
		{
			int hoanthanh = db.HocVus.Where(x => x.TinhTrang.ToString() == "True").Count();
			int chuahoanthanh = db.HocVus.Where(x => x.TinhTrang.ToString() == "False").Count();
			Ratio obj = new Ratio();
			obj.HoanThanh = hoanthanh;
			obj.ChuaHoanThanh = chuahoanthanh;

			return Json(obj, JsonRequestBehavior.AllowGet);
		}
		public class Ratio
		{
			public int HoanThanh { get; set; }
			public int ChuaHoanThanh { get; set; }
		}
	}
}

abc/Areas/Admin/Views/ThongKe/Index.cshtml
@model PagedList.IPagedList<Models.ViewModel.CustomViewThongKe>
@using PagedList.Mvc;
@{
	ViewBag.Title = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
	Thống kê
}

@using (Html.BeginForm("Index", "ThongKe", FormMethod.Get))
{
	<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
		<table>
			<tbody>
				<tr>
					<td>Tên người dùng</td>
					<td><input type="text" class="form-control small" aria-label="Search" aria-describedby="basic-addon2" name="searchName" value="@ViewBag.searchName"></td>
					<td>Email</td>
					<td><input type="text" class="form-control small" aria-label="Search" aria-describedby="basic-addon2" name="searchEmail" value="@ViewBag.searchEmail"></td>
				</tr>
				<tr>
					<td>Đơn vị</td>
					<td>
						<div>
							@Html.DropDownList("searchTenDonVi", new SelectList((IEnumerable<SelectListItem>)ViewBag.listDonVi, "Value", "Text", ViewBag.searchTenDonVi), "Chọn đơn vị", new { @class = "form-control input-group" })
						</div>
					</td>
					<td>Danh Mục</td>
					<td>
						<div>
							@Html.DropDownList("searchTenDanhMuc1", new SelectList(" "), "Chọn danh mục", new { @class = "form-control input-group" })
						</div>
					</td>

				</tr>
				<tr>
					<td>Lớp</td>
					<td>
						<div>
							@Html.DropDownList("searchTenLop", new SelectList((IEnumerable<SelectListItem>)ViewBag.listLop, "Value", "Text", ViewBag.searchTenLop), "Chọn lớp", new { @class = "form-control input-group" })
						</div>
					</td>
					<td>Vai trò</td>
					<td>
						<div>
							@Html.DropDownList("searchTenVaiTro", new SelectList((IEnumerable<SelectListItem>)ViewBag.listVaiTro, "Value", "Text", ViewBag.searchTenVaiTro), "Chọn vai trò", new { @class = "form-control input-group" })
						</div>
					</td>
				</tr>
				<tr>
					<td>Yêu cầu thêm</td>
					<td><input type="text" class="form-control small" aria-label="Search" aria-describedby="basic-addon2" name="searchYeuCau" value="@ViewBag.searchYeuCau"></td>
					<td>Tình trạng</td>
					<td>
						<div>
							@{
								List<SelectListItem> listItems = new List<SelectListItem>();
								listItems.Add(new SelectListItem
								{
									Text = "Hoàn thành",
									Value = "True"
								});
								listItems.Add(new SelectListItem
								{
									Text = "Chưa hoàn thành",
									Value = "False",
								});
							}
							@Html.DropDownList("searchTinhTrang", listItems, "Tình trạng", new { @class = "form-control input-group" })
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="input-group-append">
							<button class="btn btn-primary" type="submit" id="submit">
								<i class="fas fa-search fa-sm"></i>
							</button>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</form>
	
} 

<style>
	#chart_container{
		width:400px;
		height:400px;
		border:1px solid #ddd;
		padding: 1px;
		border-radius:4px;
	}
	#container {
		width: 400px;
		height: 400px;
		border: 1px solid #ddd;
		padding: 1px;
		border-radius: 4px;
	}
	#bangdanhmuc {
		width: 800px;
		height: 400px;
		border: 1px solid #ddd;
		padding: 1px;
		border-radius: 4px;
	}
</style>
<table>
	<tr>
		<td>
			<div id="chart_container">
				<canvas id="bar_chart"></canvas>
			</div>
		</td>
		<td>
			<div>
				<div id="container"></div>
			</div>
		</td>
	</tr>
	<tr>
		<th colspan="2">
			<div id="bangdanhmuc">
				<canvas id="thongkedanhmuc"></canvas>
			</div>
		</th>
		
	</tr>
</table>



<div class="card shadow mb-4">
	<div class="card-body">
		<div class="table-responsive">
			<div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
				<div class="row">
					<div class="col-sm-12">
						<table class="table table-bordered dataTable" width="100" cellpadding="0" role="grid" style="width: 100%;" id="myTable">
							<thead>
								<tr>
									<th>Ngày tạo</th>
									<th>Yêu cầu thêm</th>
									<th>Ngày hẹn</th>
									<th>Đơn vị</th>
									<th>Danh mục</th>
									<th>User</th>
									<th>Vai trò</th>
									<th>Lớp </th>
									<th>Email </th>
									<th>Tình trạng</th>
								</tr>
							</thead>

							<tbody>

								@foreach (var item in Model)
								{
									<tr id="row_@item.HocVuID" role="row" class="old">
										<td>@(item.NgayTao.HasValue ? item.NgayTao.Value.ToString("dd/MM/yyyy hh:mm tt") : "")</td>
										<td>@item.YeuCauThem</td>
										<td>@(item.NgayHen.HasValue ? item.NgayHen.Value.ToString("dd/MM/yyyy") : "")</td>
										<td>@item.TenDonVi</td>
										<td>@item.TenDanhMuc</td>
										<td>@item.UserName</td>
										<td>@item.TenVaiTro</td>
										<td>@item.TenLop</td>
										<td>@item.Email</td>
										<td>@(item.TinhTrang == true ? "Hoàn thành" : "Chưa hoàn thành")</td>
									</tr>
								}
							</tbody>
						</table>
						<a href="@Url.Action("ExportToExcel","HocVu")">Export Excel</a>
						|
						<p> @Html.ActionLink("Print", "PrintAll")</p>
						@Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchTenDonVi = ViewBag.searchTenDonVi }))

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="~/Assets/admin/vendor/chart.js/Chart.min.js"></script>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<link href="~/Assets/admin/css/sb-admin-2.min.css" rel="stylesheet" />
<script src="~/Assets/admin/js/sb-admin-2.min.js"></script>
<script src="~/Assets/admin/chart/exporting.js"></script>
<script src="~/Assets/admin/chart/highcharts.js"></script>

<script>
	$(document).ready(function () {
		$("#searchTenDonVi").change(function () {
			$.get("/Admin/ThongKe/GetDanhMucList", { TenDonVi: $("#searchTenDonVi").children("option").filter(":selected").text() }, function (data) {
				$("#searchTenDanhMuc").empty();
				$.each(data, function (index, row) {
					$("#searchTenDanhMuc").append("<option value='" + row.DanhMucID + "'>" + row.TenDanhMuc + "</option>")
				});
			});
		})
	});
</script>
<script>
	var repArray = @Html.Raw(Json.Encode(ViewBag.REP));
	var userID = @Html.Raw(Json.Encode(ViewBag.UserID));
	var ctx = $("#bar_chart");
	var bacChart = new Chart(ctx,{
		type: 'bar',
		data: {
			labels: userID,
			datasets: [{
				label: "Bảng thống kê người dùng",
				data: repArray,
				backgroundColor: "rgba(242,166,54,.5)",
				borderColor: "rgb(242,166,54)",
				borderWidth:1
			}]
		},
		options: {
			maintainAspectRatio: false,
			scales: {
				yAxes: [{
					ticks: {
						beginAtZero: true
					}
				}]
			}
		}
	});
</script>
<script>
	var listDanhMuc = @Html.Raw(Json.Encode(ViewBag.listDanhMuc));
	var danhmucID = @Html.Raw(Json.Encode(ViewBag.danhmucID));
	var ctx = $("#thongkedanhmuc");
	var bacChart = new Chart(ctx,{
		type: 'bar',
		data: {
			labels: danhmucID,
			datasets: [{
				label: "Bảng thống kê danh mục",
				data: listDanhMuc,
				backgroundColor: "rgba(145,65,72,.5)",
				borderColor: "rgb(145,65,72)",
				borderWidth:1
			}]
		},
		options: {
			maintainAspectRatio: false,
			scales: {
				yAxes: [{
					ticks: {
						beginAtZero: true
					}
				}]
			}
		}
	});
</script>
<script>
	$(document).ready(function () {
		$.getJSON("/Admin/ThongKe/GetData", function (data) {
			Highcharts.chart('container', {
				chart: {
					plotBackgroundColor: null,
					plotBorderWidth: null,
					plotShadow: false,
					type: 'pie'
				},
				title: {
					text: 'Biểu đồ tình trạng'
				},
				tooltip: {
					pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
				},
				plotOptions: {
					pie: {
						allowPointSelect: true,
						cursor: 'pointer',
						dataLabels: {
							enabled: true,
							format: '<b>{point.name}</b>: {point.percentage:.1f} %',
							style: {
								color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
							}
						}
					}
				},
				series: [{
					name: 'Brands',
					colorByPoint: true,
					data: [{
						name: 'Hoàn thành',
						y: data.HoanThanh
					}, {
						name: 'Chưa hoàn thành',
						y: data.ChuaHoanThanh
					}]
				}]
			});
		});
	});
</script>