abc/Controllers/LichSuController.cs
using abc.Common;
using Models.Dao;
using Models.Framework;
using Models.ViewModel;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace abc.Controllers
{
    public class LichSuController : Controller
    {
		// GET: LichSu
		DoAnDbContext db = new DoAnDbContext();
		public ActionResult Index(string searchString, int page = 1, int pageSize = 100)
		{
			User a = CheckAuthorize.Instance.XuatUserID();
			var dao = new HocVuDao();
			var model = dao.ListLichSu(searchString, page, pageSize, a);
			ViewBag.SearchString = searchString;
			List<HocVuViewModel> list = new List<HocVuViewModel>();
			using(DoAnDbContext db = new DoAnDbContext())
			{
				list = list.OrderBy(x => x.HocVuID).ToList();
			}
			return View(model);
		}
		[HttpGet]
		public ActionResult Chat(int id)
		{
			var hocvu = new HocVuDao();
			var content = hocvu.ViewDetail(id);
			return View(content);
		}
		[HttpPost]
		public ActionResult Chat(HocVu hocvu)
		{
			User a = CheckAuthorize.Instance.XuatUserID();
			if (ModelState.IsValid)
			{
				var dao = new HocVuDao();
				int id = dao.Insert2(hocvu, a, hocvu.HocVuID);
				if (id > 0)
				{
					return RedirectToAction("Index", "Home");
				}
				else
				{
					ModelState.AddModelError("", "Thêm không thành công");
				}
				
			}
			return View("Index");
		}

	}
}

abc/Views/LichSu/Chat.cshtml
@model Models.Framework.HocVu

@{
	ViewBag.Title = "Chat";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Chat", "LichSu", FormMethod.Post))
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })

	<div class="form-group" id="ParentID">
		@Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ParentID, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group" id="DonViID">
		@Html.LabelFor(model => model.DonViID, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.DonViID, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.DonViID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group" id="DanhMucID">
		@Html.LabelFor(model => model.DanhMucID, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.DanhMucID, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.DanhMucID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.YeuCauThem, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.YeuCauThem, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.YeuCauThem, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.NgayHen, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.NgayHen, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.NgayHen, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.HocVuID, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.HocVuID, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.HocVuID, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

<script>
	document.getElementById("ParentID").style.display = 'none';
	document.getElementById("DonViID").style.display = 'none';
	document.getElementById("DanhMucID").style.display = 'none';
	document.getElementById("HocVuID").style.display = 'none';
</script>

abc/Views/LichSu/Index.cshtml
@model PagedList.IPagedList<Models.ViewModel.HocVuViewModel>
@using PagedList.Mvc;
@using System.Web.Mvc.Html;

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "LichSu", FormMethod.Get))
{
	<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
		<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
			<div class="input-group">
				<input type="search" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="searchString" value="@ViewBag.SearchString">

				<div class="input-group-append">
					<button class="btn btn-primary" type="submit">
						<i class="fas fa-search fa-sm"></i>
					</button>
				</div>
			</div>
		</form>
	</nav>

}

<div class="card shadow mb-4">
	<div class="card-body">
					<div class="container">
						@NestedData.GetHtml(Model, 0)
					</div>
					@Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = ViewBag.SearchString }))


					<style>
						.container {
							min-width: 500px;
							overflow: auto;
						}

						.innerTable table {
							margin: 0px auto;
							border-left-width: 4px;
						}

						td.innerTable {
							padding-left: 20px !important;
						}

						.icon {
							background-image: url('../../Images/ui-icons_222222_256x240.png');
							background-repeat: no-repeat;
							width: 16px;
							height: 16px;
							display: inline-block;
							float: left;
						}

						.icon-e {
							background-position: -32px -16px
						}

						.icon-s {
							background-position: -64px -16px
						}
					</style>
				</div>
			</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script type="text/javascript">
	if (typeof jQuery.fn.live == 'undefined' || !(jQuery.isFunction(jQuery.fn.live))) {
		jQuery.fn.extend({
			live: function (event, callback) {
				if (this.selector) {
					jQuery(document).on(event, this.selector, callback);
				}
			}
		});
	}
	$(document).ready(function () {
		$('.icon').click(function () {
			var $pRow = $(this).parents('tr');
			var $nextRow = $pRow.next('tr');
			$nextRow.toggle();
			$(this).toggleClass('icon-s icon-e');
		});
	});
</script>