abc/Areas/Admin/Controllers/ChucNangController.cs
using abc.Models;
using Models.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace abc.Areas.Admin.Controllers
{
    public class ChucNangController : BaseController
    {
		// GET: Admin/ChucNang
		[KiemTraQuyen(PermissionName = "Admin")]
		public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
		{
			var dao = new ChucNangDao();
			var model = dao.ListAllPaging(searchString, page, pageSize);
			ViewBag.SearchString = searchString;
			return View(model);
		}
	}
}

abc/Areas/Admin/Views/ChucNang/Index.cshtml
@model PagedList.IPagedList<Models.Framework.ChucNangPhanMem>
@using PagedList.Mvc;
@{
				/**/

				ViewBag.Title = "Index";
				Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
	Danh sách chức năng
}
@using (Html.BeginForm("Index", "ChucNang", FormMethod.Get))
{
	<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
		<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
			<div class="input-group">
				<input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="searchString" value="@ViewBag.SearchString">
				<div class="input-group-append">
					<button class="btn btn-primary" type="submit">
						<i class="fas fa-search fa-sm"></i>
					</button>
				</div>
			</div>
		</form>


	</nav>
}

<div class="card shadow mb-4">
	<div class="card-body">
		<div class="table-responsive">

			<div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
				<div class="row">
					<div class="col-sm-12">
						<table class="table table-bordered dataTable" width="100" cellpadding="0" role="grid" style="width: 100%;">
							<thead>
								<tr>

									<th>Tên chức năng</th>
									
									
								</tr>
							</thead>
							<tbody>
							<tbody>

								@foreach (var item in Model)
								{
									<tr id="row_@item.ChucNangID" role="row" class="old">

										<td>@item.TenChucNang</td>
										
										
									</tr>
								}




							</tbody>
						</table>
						@Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = ViewBag.SearchString }))
					</div>
				</div>
			</div>
		</div>
	</div>
</div>